<?php

namespace Telma\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnteteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnteteRepository extends EntityRepository
{
}
