<?php

namespace Telma\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadRepository extends EntityRepository
{
}
