<?php

namespace Telma\DashboardBundle\Repository;

/**
 * RegleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegleRepository extends \Doctrine\ORM\EntityRepository
{
}
