# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Telma\UserBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
            
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern:    ^/
            anonymous:  true
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: /%locale%/dashboard
            logout:
                path:       fos_user_security_logout
                target:     /login
            remember_me:
                secret:     %secret%
                
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard/, role: ROLE_ADMIN }
        
    access_denied_url: /login
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
